/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package main

class App {
  
    static void main(String[] args) {
        def WIDTH = 20;
        def HEIGHT = 20;
        def SCALE = 15;

        def b = new Board(WIDTH,HEIGHT);
        def r = [
            new Rule(TileType.SAND, TileType.SAND),
            new Rule(TileType.FOREST, TileType.FOREST),
            new Rule(TileType.WATER, TileType.WATER),
            new Rule(TileType.STONE, TileType.STONE),
            new Rule(TileType.MOUNTAIN_TOP, TileType.MOUNTAIN_TOP),
            new Rule(TileType.MOUNTAIN_BOTTOM, TileType.MOUNTAIN_BOTTOM),
            //
            new Rule(TileType.WATER, TileType.SAND),
            new Rule(TileType.SAND, TileType.STONE),
            new Rule(TileType.WATER, TileType.FOREST),
            new Rule(TileType.FOREST, TileType.STONE),
            new Rule(TileType.STONE, TileType.MOUNTAIN_BOTTOM),
            new Rule(TileType.MOUNTAIN_BOTTOM, TileType.MOUNTAIN_TOP)
        ]
        def stepwise = new StepWise(WIDTH * SCALE,HEIGHT * SCALE, SCALE, b, r as Rule[])
        def finished = new Finished(WIDTH * SCALE,HEIGHT * SCALE, SCALE, b, r as Rule[])
        def renderer = new Renderer(stepwise)

        renderer.setUpGui()

    }
}
