/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package main

class App {
  
    static void main(String[] args) {
        def WIDTH = 20;
        def HEIGHT = 20;
        def SCALE = 15;

        Map map = new Map(WIDTH,HEIGHT);
        Rule[] r = [
            new Rule(TileType.SAND, TileType.SAND),
            new Rule(TileType.FOREST, TileType.FOREST),
            new Rule(TileType.WATER, TileType.WATER),
            new Rule(TileType.STONE, TileType.STONE),
            new Rule(TileType.MOUNTAIN_TOP, TileType.MOUNTAIN_TOP),
            new Rule(TileType.MOUNTAIN_BOTTOM, TileType.MOUNTAIN_BOTTOM),
            //
            new Rule(TileType.WATER, TileType.SAND),
            new Rule(TileType.SAND, TileType.STONE),
            new Rule(TileType.WATER, TileType.FOREST),
            new Rule(TileType.FOREST, TileType.STONE),
            new Rule(TileType.STONE, TileType.MOUNTAIN_BOTTOM),
            new Rule(TileType.MOUNTAIN_BOTTOM, TileType.MOUNTAIN_TOP)
        ] 

        def gen = new Generator(map, r)
        def stepwise = new StepWise(WIDTH * SCALE,HEIGHT * SCALE, SCALE, gen)
        def finished = new Finished(WIDTH * SCALE,HEIGHT * SCALE, SCALE, gen)
        def renderer = new Renderer(stepwise)

        renderer.setUpGui()

    }
}
